/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finalisasi;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author UseR
 */
public class OKKasir extends javax.swing.JFrame {
    public int subTotalBelanja, baris, jumlahBaris;
    public int jmlBeli,hrgSatuan;
    boolean barisTerpilih;
    
    DefaultTableModel model;
    /**
     * Creates new form OKKasir
     */
    public OKKasir() {
        initComponents();
        model = (DefaultTableModel) tblPenjualan.getModel();
        getCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJml = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MART");

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SMEGA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(120, 120, 120))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarangItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setText("Rp.");

        lblHarga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(255, 51, 51));
        lblHarga.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setText("Jumlah");

        txtJml.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtJmlCaretUpdate(evt);
            }
        });
        txtJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJmlKeyPressed(evt);
            }
        });

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Satuan", "Jumlah Beli", "Sub Total"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenjualan);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total");

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        lblTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        lblTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSubtotal.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(249, 249, 249))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubtotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarangItemStateChanged
        // TODO add your handling code here:
        getLabel();
    }//GEN-LAST:event_cmbBarangItemStateChanged

    private void txtJmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyPressed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblPenjualan.getModel();
            List list = new ArrayList<>(); //List adalah class dan list adalah variabel
            tblPenjualan.setAutoCreateColumnsFromModel(true);
            list.add(cmbBarang.getSelectedItem().toString());
            list.add(lblHarga.getText()); 
            list.add(txtJml.getText());
            
            
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){ //tekan enter
                if(barisTerpilih){
                    btnEditClick();
                }else{
                    subtotal();
                    list.add(String.valueOf(subTotalBelanja));
                    model.addRow(list.toArray());  
                    bersihkanLayar();
                    total();
                }
            }
            
            if(evt.getKeyCode()== KeyEvent.VK_DELETE){
                if(barisTerpilih){
                    keyDelete();
                    int selectedRow = tblPenjualan.getSelectedRow();
                    model = (DefaultTableModel) tblPenjualan.getModel();
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
                }
            }
            
            
    }//GEN-LAST:event_txtJmlKeyPressed

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        // TODO add your handling code here:
        mouseClicked();
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void txtJmlCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtJmlCaretUpdate
        // TODO add your handling code here:
        int subtotal;
        subtotal = Integer.parseInt(lblHarga.getText())*(Integer.parseInt(txtJml.getText()));
        lblSubtotal.setText(String.valueOf(subtotal));
        //subtotalnya harus di tambah ke tabel dulu
    }//GEN-LAST:event_txtJmlCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OKKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OKKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OKKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OKKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OKKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtJml;
    // End of variables declaration//GEN-END:variables

    private void getLabel() {
        String fieldNama;
        fieldNama = (String) cmbBarang.getSelectedItem();
        try{
            Statement stat3 = (Statement) koneksi.getKoneksi( ).createStatement( );
            String sql3 = "Select harga from penjualan where nama_barang='"+fieldNama+"'";
            ResultSet res3 = stat3.executeQuery(sql3);
            while(res3.next())
            {
              lblHarga.setText(res3.getString("harga"));
            }
        }catch (SQLException ex){
//            Logger.getLogger(FormBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnEditClick() {
        model = (DefaultTableModel) tblPenjualan.getModel();
        int baris = tblPenjualan.getSelectedRow();
        int row = baris;

        if (baris >= 0) {
        
            String namaBarang = (String) cmbBarang.getSelectedItem();
            String hargaSatuan = (String) lblHarga.getText();
            String jumlahBeli = (String) txtJml.getText();
            subtotal();


            model.setValueAt(namaBarang, baris, 0);
            model.setValueAt(hargaSatuan, baris, 1);
            model.setValueAt(jumlahBeli, baris, 2);
            model.setValueAt(subTotalBelanja, baris, 3);
            
            total();
            bersihkanLayar();
            cekBarisTerpilih();
            
            tblPenjualan.clearSelection();
            barisTerpilih=false;
 
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");
            
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan di-update terlebih dahulu.");
        }
       
      total();  
    }

    private void mouseClicked() {
        model = (DefaultTableModel) tblPenjualan.getModel();
       baris = tblPenjualan.getSelectedRow();
       barisTerpilih=true;
         
       txtJml.setText(String.valueOf(baris));
       String namaBarang = (String) tblPenjualan.getValueAt(baris, 0);
       String hargaSatuan = (String) tblPenjualan.getValueAt(baris, 1);
       String jumlahBeli = (String) tblPenjualan.getValueAt(baris, 2);
       String subTotal = (String) tblPenjualan.getValueAt(baris, 3);
        
       int hrgSat = Integer.parseInt(hargaSatuan);
       int jmlBeli = Integer.parseInt(jumlahBeli);
       int sub2=hrgSat*jmlBeli;
       
       int row = baris;
       
       model.setValueAt(namaBarang, row, 0);
       model.setValueAt(hargaSatuan, row, 1);
       model.setValueAt(jumlahBeli, row, 2);
       
       cmbBarang.setSelectedItem(namaBarang.toString());
       txtJml.setText(jumlahBeli);
       
        if(namaBarang.equals("Es Krim")){
            cmbBarang.setSelectedIndex(1);
       }else if(namaBarang.equals("Chitato")){
            cmbBarang.setSelectedIndex(2);
        }else if(namaBarang.equals("Sikat Gigi")){
            cmbBarang.setSelectedIndex(3);
        }else if(namaBarang.equals("Pepsodent")){
            cmbBarang.setSelectedIndex(4);
        }else{
           cmbBarang.setSelectedIndex(0);
       }
        
        lblHarga.setText(hargaSatuan);
        txtJml.setText(jumlahBeli);
        lblTotal.setText(subTotal);
    }

    private int subtotal() {
        jmlBeli = Integer.valueOf(txtJml.getText());
        hrgSatuan = Integer.valueOf(lblHarga.getText());
        subTotalBelanja=jmlBeli*hrgSatuan;
        return subTotalBelanja;
    }

    private void bersihkanLayar() {
        txtJml.setText("");
       lblHarga.setText("0");
       cmbBarang.setSelectedIndex(0);
    }

    private void total() {
        model = (DefaultTableModel) tblPenjualan.getModel();
        int jumlah = model.getRowCount();
        int sumTotal = 0;
        
        for (int i = 0; i < jumlah; i++) {
            int dataTotal = Integer.valueOf(model.getValueAt(i, 3).toString()); //i, 3 itu adalah kolom ke berapa yg mau ditampilkan jumlahnya. jadi i, 3 adalah kolom subtotal karna index dihitung dari 0.
            sumTotal += dataTotal;
        }
        lblTotal.setText(Integer.toString(sumTotal));     
    }

    private void keyDelete() {
        barisTerpilih=false;
        cmbBarang.setSelectedIndex(0);
        lblHarga.setText("0");
        txtJml.setText("");
        lblTotal.setText("0");
    }

    private boolean cekBarisTerpilih() {
        return true;
    }

    private void getCombo() {
        try{
           Statement stat = (Statement) koneksi.getKoneksi( ).createStatement( );
           String sql        = "SELECT * FROM penjualan";
           ResultSet res   = stat.executeQuery(sql);
           cmbBarang.addItem("- Pilih Nama Barang -");
           while(res.next ())
           {
                cmbBarang.addItem(res.getString("nama_barang"));
           }
      }catch(Exception ex)
      {
          
      }
    }
}
